routeringcentrale:
    image: reg-t1.modernodam.nl:5000/brp/gba-levering-routering-centrale:latest
    extrahosts:
        - "activemqdb:127.0.0.1"
        - "brpdb:127.0.0.1"
        - "archiveringdb:127.0.0.1"
        - "lockingdb:127.0.0.1"
    environment:
        - ACTIVEMQDB_ENV_DBUSER=brp
        - ACTIVEMQDB_ENV_DBPASS=brp
        - ACTIVEMQDB_PORT_5432_TCP_PORT=5433
        - BRPDB_ENV_DBUSER=brp
        - BRPDB_ENV_DBPASS=brp
        - BRPDB_PORT_5432_TCP_PORT=5432
        - ARCHIVERINGDB_ENV_DBUSER=brp
        - ARCHIVERINGDB_ENV_DBPASS=brp
        - ARCHIVERINGDB_PORT_5432_TCP_PORT=5432
        - LOCKINGDB_ENV_DBUSER=brp
        - LOCKINGDB_ENV_DBPASS=brp
        - LOCKINGDB_PORT_5432_TCP_PORT=5432
    ports:
        - "61616:61616"
        - "18080:8080"
