#
# BRP Databases
#
brpdatabase:
  image: brp/database
  container_name: brpdb
  net: brp
  ports:
    - "5432:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

activemqdatabase:
  image: brp/database
  container_name: activemqdb
  net: brp
  ports:
    - "5442:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

archiveringdatabase:
  image: brp/database
  container_name: archiveringdb
  net: brp
  ports:
    - "5452:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

lockingdatabase:
  image: brp/database
  container_name: lockingdb
  net: brp
  ports:
    - "5462:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

kerndatabase:
  image: brp/database
  container_name: kerndb
  net: brp
  ports:
    - "5472:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

#
# BRP Overig
#
sleutelbos:
  image: fac-reg.modernodam.nl:5000/sleutel
  container_name: sleutebos
  net: brp
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==brpapp

#
# BRP Message broker
#
brpmessagebroker:
  image: brp/brp-message-broker
  container_name: routeringcentrale
  net: brp
  ports:
    - "11990:11990"
    - "61616:61616"
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==brpapp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ACTIVEMQDB_ENV_HOSTNAME: activemqdb
    ACTIVEMQDB_PORT_5432_TCP_PORT: 5432
    ACTIVEMQDB_ENV_DBNAME: brp
    ACTIVEMQDB_ENV_DBUSER: brp
    ACTIVEMQDB_ENV_DBPASS: brp
    JAVA_OPTS: -Xms128M -Xmx1G
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11990
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# BRP Componenten
#
brpgbacentrale:
  image: brp/gba-centrale
  container_name: brpgbacentrale
  net: brp
  ports:
    - "11991:11991"
  volumes:
    - /opt/appserver/logs
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    LOCKINGDB_ENV_DBPASS: brp
    ISCROUTERING_ENV_PORT: 61616
    ISCROUTERING_ENV_HOSTNAME: iscroutering
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11991
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

mutatielevering:
  image: brp/mutatielevering
  container_name: mutatielevering
  net: brp
  ports:
    - "8180:8080"
    - "11992:11992"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    JAVA_OPTS: -Xms128M -Xmx1G
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11992
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

synchronisatie:
  image: brp/synchronisatie
  container_name: synchronisatie
  net: brp
  ports:
    - "8380:8080"
    - "11993:11993"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    JAVA_OPTS: -Xms64M -Xmx512M
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11993
  volumes_from:
    - sleutelbos
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

afnemerindicaties:
  image: brp/onderhoud-afnemerindicaties
  container_name: afnemerindicaties
  net: brp
  ports:
    - "8480:8080"
    - "11994:11994"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    JAVA_OPTS: -Xms64M -Xmx512M
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11994
  volumes_from:
    - sleutelbos
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

verzending:
  image: brp/verzending
  container_name: verzending
  net: brp
  ports:
    - "8580:8080"
    - "11995:11995"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    JAVA_OPTS: -Xms128M -Xmx1G
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11995
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

protocollering:
  image: brp/protocollering
  container_name: protocollering
  net: brp
  ports:
    - "8680:8080"
    - "11996:11996"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    JAVA_OPTS: -Xms32M -Xmx256M
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11996
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

bijhouding:
  image: brp/bijhouding
  container_name: bijhouding
  net: brp
  ports:
    - "8780:8080"
    - "11997:11997"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_DBNAME: brp
    BRPDB_ENV_DBUSER: brp
    BRPDB_ENV_DBPASS: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_DBNAME: brp
    ARCHIVERINGDB_ENV_DBUSER: brp
    ARCHIVERINGDB_ENV_DBPASS: brp
    LOCKINGDB_ENV_HOSTNAME: lockingdb
    LOCKINGDB_PORT_5432_TCP_PORT: 5432
    LOCKINGDB_ENV_DBNAME: brp
    LOCKINGDB_ENV_DBUSER: brp
    ROUTERINGCENTRALE_PORT_61616_TCP_PORT: 61616
    ROUTERINGCENTRALE_ENV_HOSTNAME: routeringcentrale
    SLEUTELBOS_ENV_PRIVATEFILE: /keystores/privatestore.jks
    SLEUTELBOS_ENV_PRIVATEKEY: serverkey
    SLEUTELBOS_ENV_PRIVATEPASSWORD: privatestore
    SLEUTELBOS_ENV_PUBLICFILE: /keystores/publicstore.jks
    SLEUTELBOS_ENV_PUBLICPASSWORD: publicstore
    SLEUTELBOS_ENV_PRIVATEKEYPASSWORD: serverkeypassword
    JAVA_OPTS: -Xms64M -Xmx512M
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 11997
  volumes_from:
      - sleutelbos
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Beheer applicatie
#
beheer:
  image: brp/beheer
  container_name: beheer
  net: brp
  ports:
    - "8280:8080"
  environment:
    constraint: rol==brpapp
    BRPDB_ENV_HOSTNAME: brpdb
    BRPDB_PORT_5432_TCP_PORT: 5432
    BRPDB_ENV_NAME: brp
    BRPDB_ENV_USERNAME: brp
    BRPDB_ENV_PASSWORD: brp
    ARCHIVERINGDB_ENV_HOSTNAME: archiveringdb
    ARCHIVERINGDB_PORT_5432_TCP_PORT: 5432
    ARCHIVERINGDB_ENV_NAME: brp
    ARCHIVERINGDB_ENV_USERNAME: brp
    ARCHIVERINGDB_ENV_PASSWORD: brp
    KERNDB_ENV_HOSTNAME: brpdb
    KERNDB_PORT_5432_TCP_PORT: 5432
    KERNDB_ENV_NAME: brp
    KERNDB_ENV_USERNAME: brp
    KERNDB_ENV_PASSWORD: brp
    PROTOCOLLERINGDB_ENV_HOSTNAME: brpdb
    PROTOCOLLERINGDB_PORT_5432_TCP_PORT: 5432
    PROTOCOLLERINGDB_ENV_NAME: brp
    PROTOCOLLERINGDB_END_USERNAME: brp
    PROTOCOLLERINGDB_ENV_PASSWORD: brp
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Migratie databases
#
iscrouteringdatabase:
  image: migr-routering-database
  container_name: iscrouteringdatabase
  net: brp
  ports:
    - "5532:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

iscdatabase:
  image: migr-isc-database
  container_name: iscdatabase
  net: brp
  ports:
    - "5732:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

voiscdatabase:
  image: migr-voisc-database
  container_name: voiscdatabase
  net: brp
  ports:
    - "5632:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

#
# Migratie message broker
#
iscroutering:
  image: migr-routering-runtime
  container_name: iscroutering
  net: brp
  ports:
    - "1199:1199"
    - "61617:61616"
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    ROUTERING_DB_ENV_HOSTNAME: iscrouteringdatabase
    ROUTERING_DB_ENV_PORT: 5432
    ROUTERING_DB_ENV_NAME: routering
    ROUTERING_DB_ENV_USERNAME: migratie
    ROUTERING_DB_ENV_PASSWORD: M1gratie
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1199
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Migratie componenten
#
iscsynchronisatie:
  image: migr-synchronisatie-runtime
  container_name: iscsynchronisatie
  net: brp
  ports:
    - "1799:1799"
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    BRP_DB_ENV_HOSTNAME: brpdb
    BRP_DB_ENV_PORT: 5432
    BRP_DB_ENV_NAME: brp
    BRP_DB_ENV_USERNAME: brp
    BRP_DB_ENV_PASSWORD: brp
    ROUTERING_ENV_PORT: 61616
    ROUTERING_ENV_HOSTNAME: iscroutering
    BRPROUTERING_ENV_PORT: 61616
    BRPROUTERING_ENV_HOSTNAME: routeringcentrale
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1799
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"


isc:
  image: migr-isc-runtime
  container_name: isc
  net: brp
  ports:
    - "1099:1099"
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    ISC_DB_ENV_HOSTNAME: iscdatabase
    ISC_DB_ENV_PORT: 5432
    ISC_DB_ENV_NAME: isc
    ISC_DB_ENV_USERNAME: migratie
    ISC_DB_ENV_PASSWORD: M1gratie
    ROUTERING_ENV_PORT: 61616
    ROUTERING_ENV_HOSTNAME: iscroutering
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1099
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

iscconsole:
  image: migr-isc-console
  container_name: iscconsole
  net: brp
  ports:
    - "8080:8080"
  volumes:
    - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    ISC_DB_ENV_HOSTNAME: iscdatabase
    ISC_DB_ENV_PORT: 5432
    ISC_DB_ENV_NAME: isc
    ISC_DB_ENV_USERNAME: migratie
    ISC_DB_ENV_PASSWORD: M1gratie
    ISC_ENV_JMX_HOSTNAME: isc
    ISC_ENV_JMX_PORT: 1099
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

voisc:
  image: migr-voisc-runtime
  container_name: voisc
  net: brp
  ports:
    - "1399:1399"
  volumes:
    - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    VOISC_DB_ENV_HOSTNAME: voiscdatabase
    VOISC_DB_ENV_PORT: 5432
    VOISC_DB_ENV_NAME: voisc
    VOISC_DB_ENV_USERNAME: migratie
    VOISC_DB_ENV_PASSWORD: M1gratie
    MAILBOX_ENV_HOSTNAME: mailbox
    MAILBOX_ENV_PORT: 1212
    ROUTERING_ENV_PORT: 61616
    ROUTERING_ENV_HOSTNAME: iscroutering
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1399
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Migratie componenten (IV)
#
iscsynchronisatienaarbrp:
  image: migr-synchronisatie-runtime-naarbrp
  container_name: iscsynchronisatienaarbrp
  net: brp
  ports:
    - "1899:1899"
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    BRP_DB_ENV_HOSTNAME: brpdb
    BRP_DB_ENV_PORT: 5432
    BRP_DB_ENV_NAME: brp
    BRP_DB_ENV_USERNAME: brp
    BRP_DB_ENV_PASSWORD: brp
    IV_ROUTERING_ENV_HOSTNAME: hornetq
    IV_ROUTERING_ENV_PORT: 5445
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1899
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

iscsynchronisatienaarlo3:
  image: migr-synchronisatie-runtime-naarlo3
  container_name: iscsynchronisatienaarlo3
  net: brp
  ports:
    - "1999:1999"
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    BRP_DB_ENV_HOSTNAME: brpdb
    BRP_DB_ENV_PORT: 5432
    BRP_DB_ENV_NAME: brp
    BRP_DB_ENV_USERNAME: brp
    BRP_DB_ENV_PASSWORD: brp
    IV_ROUTERING_ENV_HOSTNAME: hornetq
    IV_ROUTERING_ENV_PORT: 5445
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1999
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

isclogging:
  image: migr-init-logging-runtime
  container_name: isclogging
  net: brp
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    BRP_DB_ENV_HOSTNAME: brpdb
    BRP_DB_ENV_PORT: 5432
    BRP_DB_ENV_NAME: brp
    BRP_DB_ENV_USERNAME: brp
    BRP_DB_ENV_PASSWORD: brp
    GBAV_DB_ENV_HOSTNAME: gbavdatabase
    GBAV_DB_ENV_PORT: 5432
    GBAV_DB_ENV_NAME: gbav
    GBAV_DB_ENV_USERNAME: migratie
    GBAV_DB_ENV_PASSWORD: M1gratie
    IV_ROUTERING_ENV_HOSTNAME: hornetq
    IV_ROUTERING_ENV_PORT: 5445

  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

hornetq:
  image: migr-tools-hornetq
  container_name: hornetq
  net: brp
  ports:
    - "2090:2090"
    - "5445:5445"
  environment:
    constraint: rol==migrapp
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 2090
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Migratie overig
#
mailbox:
  image: migr-tools-mailbox
  container_name: mailbox
  net: brp
  ports:
    - "1599:1599"
    - "1212:1212"
  environment:
    constraint: rol==migrapp
    JMX_HOST: ${DOCKER_IP}
    JMX_PORT: 1599
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Migratie overig (IV)
#
gbavdatabase:
  image: migr-tools-gbav-database
  container_name: gbavdatabase
  net: brp
  ports:
    - "5832:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

ggodatabase:
  image: migr-ggo-viewer-database
  container_name: ggodatabase
  net: brp
  ports:
    - "5932:5432"
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

ggoviewer:
  image: migr-ggo-viewer
  container_name: ggoviewer
  net: brp
  volumes:
      - /opt/appserver/logs
  environment:
    constraint: rol==migrapp
    GGOVIEWER_BRP_DB_ENV_HOSTNAME: brpdb
    GGOVIEWER_BRP_DB_ENV_PORT: 5432
    GGOVIEWER_BRP_DB_ENV_NAME: brp
    GGOVIEWER_BRP_DB_ENV_USERNAME: brp
    GGOVIEWER_BRP_DB_ENV_PASSWORD: brp
    GGOVIEWER_VIEWER_DB_ENV_HOST: gbavdatabase
    GGOVIEWER_VIEWER_DB_ENV_NAME: gbav
    GGOVIEWER_VIEWER_DB_ENV_USERNAME: migratie
    GGOVIEWER_VIEWER_DB_ENV_PASSWORD: M1gratie
    GGOVIEWER_DEMOMODE: 'false'
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

#
# Logging
#
elasticsearch:
  image: brp/logging-elasticsearch
  container_name: elasticsearch
  net: brp
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db

kibana:
  image: brp/logging-kibana
  container_name: kibana
  net: brp
  ports:
    - "5601:5601"
  environment:
    constraint: rol==db
    ELASTICSEARCH_URL: http://elasticsearch:9200
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"

logstash:
  image: brp/logging-logstash
  container_name: logstash
  net: brp
  log_driver: "json-file"
  log_opt:
    max-size: "1m"
    max-file: "5"
  environment:
    constraint: rol==db
